services:
  - type: web
    name: bupt-ai-frontend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev -- -p 3005
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cyntigdggdg.onrender.com
      - key: NODE_ENV
        value: development
