services:
  - type: web
    name: bupt-ai-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cyntigdggdg.onrender.com
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NODE_VERSION
        value: 20
