"use client";

import * as React from "react";
import Image from "next/image";
import { AppShell } from "@/components/layout/app-shell";
import { CourseSelector } from "@/components/dashboard/course-selector";
import { Button } from "@/components/ui/button";
import { WhatsAppIcon, InstagramIcon, XIcon } from "@/components/ui/social-icons";
import { toast } from "sonner";
import { generatePractice, updateProgress } from "@/lib/api";
import type { PracticeQuestion } from "@/lib/api";
import { getUser } from "@/lib/auth";

import { useCourseSelection } from "@/lib/hooks/use-course-selection";

export default function PracticePage() {
  const { selection } = useCourseSelection();
  const [loading, setLoading] = React.useState(false);
  const [questions, setQuestions] = React.useState<PracticeQuestion[]>([]);
  const [currentIndex, setCurrentIndex] = React.useState(0);
  const [selectedAnswer, setSelectedAnswer] = React.useState<string | null>(null);
  const [showResult, setShowResult] = React.useState(false);
  const [score, setScore] = React.useState({ correct: 0, total: 0 });
  const [practiceStarted, setPracticeStarted] = React.useState(false);

  const currentQuestion = questions[currentIndex];

  const startPractice = async () => {
    if (!selection.department || !selection.course) {
      toast.error("Selection required", { description: "Please select a department and course first." });
      return;
    }
    setLoading(true);

    try {
      const result = await generatePractice(
        selection.department,
        selection.course,
        "general",
        5,
        "medium"
      );
      setQuestions(result.questions);
      setCurrentIndex(0);
      setScore({ correct: 0, total: 0 });
      setSelectedAnswer(null);
      setShowResult(false);
      setPracticeStarted(true);
    } catch (error) {
      const msg = error instanceof Error ? error.message : "Failed to generate questions.";
      toast.error("Practice Error", { description: msg });
    } finally {
      setLoading(false);
    }
  };

  const submitAnswer = async () => {
    if (!selectedAnswer || !currentQuestion) return;

    const isCorrect = selectedAnswer === currentQuestion.correctAnswer ||
      selectedAnswer === currentQuestion.expectedAnswer;

    setShowResult(true);
    setScore(prev => ({
      correct: prev.correct + (isCorrect ? 1 : 0),
      total: prev.total + 1,
    }));

    const user = getUser();
    if (user?._id) {
      try {
        await updateProgress(user._id, selection.course, "general", isCorrect);
      } catch {
        // Progress update failed silently
      }
    }

    if (isCorrect) {
      toast.success("Correct! 🎉");
    } else {
      toast.error("Not quite right", {
        description: currentQuestion.explanation,
        duration: 5000,
      });
    }
  };

  const nextQuestion = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(prev => prev + 1);
      setSelectedAnswer(null);
      setShowResult(false);
    } else {
      toast.success(`Practice complete! Final Score: ${score.correct}/${questions.length}`, {
        duration: 5000,
      });
      setPracticeStarted(false);
    }
  };

  const shareToPlatform = (platform: string) => {
    toast.success(`Sharing to ${platform}...`, {
      description: "Opening share dialog."
    });
  };

  return (
    <AppShell>
      <div className="flex w-full flex-col gap-6">
        <section className="space-y-2">
          <h1 className="text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">
            Practice session
          </h1>
          <p className="max-w-2xl text-sm text-muted-foreground">
            Choose your course and topic, then attempt questions generated by the AI tutor.
            Visual feedback and explanations help you learn as you go.
          </p>
        </section>

        <CourseSelector />

        {!practiceStarted ? (
          <section className="flex flex-col items-center gap-4 rounded-2xl border border-border bg-white/80 p-8 shadow-sm text-center">
            <div className="relative h-24 w-24 overflow-hidden rounded-full border border-primary/20 bg-white p-1 shadow-sm">
              <Image
                src="/owl-tutor.png"
                alt="Owl Tutor"
                fill
                className="object-contain"
              />
            </div>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold text-slate-900">Ready to practice?</h2>
              <p className="max-w-md text-sm text-muted-foreground">
                Select a department and course above, then click the button below to generate practice questions.
              </p>
            </div>
            <Button
              disabled={loading}
              onClick={() => startPractice()}
            >
              {loading ? "Generating..." : "Start Practice Session"}
            </Button>
          </section>
        ) : (
          <section className="grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1.5fr)]">
            <div className="flex flex-col gap-3 rounded-2xl border border-border bg-white/80 p-4 shadow-sm sm:p-5">
              <header className="flex items-center justify-between gap-2">
                <div>
                  <h2 className="text-sm font-semibold tracking-tight text-slate-900">
                    Your Progress
                  </h2>
                  <p className="text-xs text-muted-foreground">
                    Question {currentIndex + 1} of {questions.length}
                  </p>
                </div>
                <span className="rounded-full bg-primary-soft/80 px-2 py-1 text-[11px] font-medium text-primary">
                  Score: {score.correct}/{score.total}
                </span>
              </header>

              <div className="mt-4 flex flex-col gap-2">
                {questions.map((_, i) => (
                  <div
                    key={i}
                    className={`h-1.5 w-full rounded-full ${i < currentIndex ? 'bg-primary' : i === currentIndex ? 'bg-primary/40' : 'bg-muted'
                      }`}
                  />
                ))}
              </div>
            </div>

            <div className="flex flex-col gap-3 rounded-2xl border border-border bg-white/80 p-4 shadow-sm sm:p-5">
              <header className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-3">
                  <div className="relative h-10 w-10 overflow-hidden rounded-full border border-primary/10 bg-white p-1 shadow-sm">
                    <Image
                      src="/owl-tutor.png"
                      alt="Owl Tutor"
                      fill
                      className="object-contain"
                    />
                  </div>
                  <div>
                    <h2 className="text-sm font-semibold tracking-tight text-slate-900">
                      Owl Tutor
                    </h2>
                    <p className="text-[10px] text-muted-foreground uppercase tracking-wider">
                      Practice Mode
                    </p>
                  </div>
                </div>
              </header>

              <div className="mt-2 space-y-4">
                <div className="rounded-xl bg-primary-soft/30 p-4 text-sm text-slate-900 leading-relaxed shadow-sm">
                  {currentQuestion?.question}
                </div>

                {currentQuestion?.options && (
                  <div className="grid gap-2 sm:grid-cols-2">
                    {currentQuestion.options.map((option) => (
                      <button
                        key={option}
                        disabled={showResult}
                        onClick={() => setSelectedAnswer(option)}
                        className={`rounded-xl border p-3 text-left text-xs transition-all ${selectedAnswer === option
                          ? "border-primary bg-primary text-white"
                          : "border-border bg-white hover:border-primary/50 hover:bg-primary-soft/20"
                          } ${showResult && option === (currentQuestion.correctAnswer || currentQuestion.expectedAnswer)
                            ? "border-green-500 bg-green-50 text-green-700 ring-1 ring-green-500"
                            : ""
                          }`}
                      >
                        {option}
                      </button>
                    ))}
                  </div>
                )}

                <div className="flex gap-2">
                  {!showResult ? (
                    <Button
                      disabled={!selectedAnswer}
                      className="w-full"
                      onClick={submitAnswer}
                    >
                      Check Answer
                    </Button>
                  ) : (
                    <Button className="w-full" onClick={nextQuestion}>
                      {currentIndex < questions.length - 1 ? "Next Question" : "Finish Practice"}
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </section>
        )}

        <section className="grid gap-4 rounded-2xl border border-border bg-white/80 p-4 text-xs text-muted-foreground shadow-sm sm:grid-cols-[minmax(0,1.5fr)_minmax(0,1.2fr)] sm:p-5">
          <div>
            <h2 className="text-sm font-semibold text-slate-900">
              Session Summary
            </h2>
            <p className="mt-1">
              Your points and accuracy are tracked to personalize your learning journey.
            </p>
          </div>
          <div className="flex flex-col items-start gap-3">
            <h3 className="text-sm font-semibold text-slate-900">
              Share your progress
            </h3>
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                onClick={() => shareToPlatform("WhatsApp")}
                variant="outline"
                size="sm"
                className="h-8 gap-1.5 border-green-200 text-green-700 hover:bg-green-50"
              >
                <WhatsAppIcon className="h-3.5 w-3.5" />
                WhatsApp
              </Button>
              <Button
                type="button"
                onClick={() => shareToPlatform("Instagram")}
                variant="outline"
                size="sm"
                className="h-8 gap-1.5 border-pink-200 text-pink-700 hover:bg-pink-50"
              >
                <InstagramIcon className="h-3.5 w-3.5" />
                Instagram
              </Button>
              <Button
                type="button"
                onClick={() => shareToPlatform("X")}
                variant="outline"
                size="sm"
                className="h-8 gap-1.5 border-slate-300 text-slate-700 hover:bg-slate-50"
              >
                <XIcon className="h-3.5 w-3.5" />
                X
              </Button>
            </div>
          </div>
        </section>
      </div>
    </AppShell>
  );
}
